# airflow/agents/blog_agents.py
"""
All blog pipeline agent functions.

Models used:
  - README Writer   : Gemini Flash (fast, instruction-following)
  - Researcher      : Gemini Pro with structured output (strict JSON schema)
  - Code Narrator   : Claude 3.5 Sonnet via GitHub Models (best code comprehension)
  - Ghostwriter     : Llama 3.3 70B via Groq (fast, natural prose)
  - Editor          : Gemini Flash (formatting + SEO)
  - Refiner         : Gemini Flash (targeted revision)
  - Idea Expander   : Gemini Pro with structured output
  - Code Commenter  : Gemini Flash (instruction following, no logic changes)
  - Code Improver   : Gemini Pro (deep reasoning for code review)

All API keys are pulled from GCP Secret Manager via get_key().
Never hardcode credentials here.

DIFFICULTY SYSTEM
-----------------
Each idea generated by agent_researcher is tagged with one of three difficulty levels:

  starter   — completable in 1-2 evenings, 1-2 tools, teaches one clear concept.
              The MVP described must be something a reader could reproduce in a
              single sitting. No more than 2 integrations.

  weekend   — completable in a weekend, 2-3 tools, teaches a small system or
              integration pattern. A motivated reader could finish the project
              over Saturday and Sunday.

  ambitious — multi-week project, complex architecture. Generated sparingly
              (roughly 1 in 5 ideas). Included to keep the backlog interesting
              but not to dominate it.

TARGET DISTRIBUTION per 5-idea batch: 2 starter, 2 weekend, 1 ambitious.

IDEA TYPE SYSTEM
----------------
  existing_asset — something already built in the author's projects.
                   The article is about lessons, decisions, and retrospective.

  new_build      — a net-new project to build before writing the article.
                   Must be MVP-scoped to the difficulty tag.

  tutorial       — a focused how-to that needs no original project.
                   Explains one technique, tool, or concept clearly using
                   the author's existing experience as the lens. These are
                   the lowest-friction posts to write and often get the most
                   search traffic.

TARGET MIX per 5-idea batch: 1 existing_asset, 3 new_build, 1 tutorial.
"""

import json
import logging
import os
import requests
import time

log = logging.getLogger(__name__)


# ── KEY HELPERS ───────────────────────────────────────────────────────────────

def _gemini_key() -> str:
    from gcp_secrets import get_key
    return get_key("Gemini-API")

def _groq_key() -> str:
    from gcp_secrets import get_key
    return get_key("Groq-API")

def _github_token() -> str:
    from gcp_secrets import get_key
    return get_key("GitHub-Models-Token")


# ── SHARED CALL HELPERS ───────────────────────────────────────────────────────

def _gemini_flash(system: str, prompt: str) -> str:
    """Calls Gemini Flash for fast, instruction-following tasks."""
    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-3.1-flash-lite-preview:generateContent?key={_gemini_key()}"
    )
    payload = {
        "systemInstruction": {"parts": [{"text": system}]},
        "contents": [{"parts": [{"text": prompt}]}],
    }
    resp = requests.post(url, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json()["candidates"][0]["content"]["parts"][0]["text"]

def _gemini_flash_2_5(system: str, prompt: str) -> str:
    """Calls Gemini 2.5 Flash for fast, instruction-following tasks."""
    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-2.5-flash:generateContent?key={_gemini_key()}"
    )
    payload = {
        "systemInstruction": {"parts": [{"text": system}]},
        "contents": [{"parts": [{"text": prompt}]}],
    }
    resp = requests.post(url, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json()["candidates"][0]["content"]["parts"][0]["text"]

def _gemini_pro_json(system: str, prompt: str, schema: dict, retries: int = 3) -> str:
    """Calls Gemini Pro with structured JSON output."""
    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-3-flash-preview:generateContent?key={_gemini_key()}"
    )
    payload = {
        "systemInstruction": {"parts": [{"text": system}]},
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": schema,
        },
    }
    for attempt in range(retries):
        try:
            resp = requests.post(url, json=payload, timeout=90)
            resp.raise_for_status()
            return resp.json()["candidates"][0]["content"]["parts"][0]["text"]
        except Exception as exc:
            if "503" in str(exc) or "Service Unavailable" in str(exc):
                if attempt < retries - 1:
                    wait = 5 ** attempt
                    log.warning("Gemini 503, retrying in %ds (attempt %d/%d)", wait, attempt+1, retries)
                    time.sleep(wait)
                    continue
            raise
    raise RuntimeError("Gemini unavailable after retries")


def _claude_sonnet(system: str, prompt: str) -> str:
    """Calls Claude 3.5 Sonnet via GitHub Models for code comprehension tasks."""
    url = "https://models.inference.ai.azure.com/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {_github_token()}",
    }
    payload = {
        "model": "Anthropic-Claude-3-5-Sonnet",
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.3,
        "max_tokens": 4096,
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=90)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


def _groq_llama(system: str, prompt: str, temperature: float = 0.7) -> str:
    """Calls Llama 3.3 70B via Groq for fast natural prose generation."""
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {_groq_key()}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        "temperature": temperature,
        "max_tokens": 8192,
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=90)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


# ── BLUEPRINT JSON SCHEMA ──────────────────────────────────────────────────────
# Used by agent_researcher (array of these) and agent_idea_expander (single item).
# The researcher schema is expanded to include difficulty and idea_type fields.

_BLUEPRINT_ITEM_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "project_type": {
            "type": "STRING",
            "description": (
                "existing_asset — something already built, article covers lessons and decisions. "
                "new_build — a net-new project to build before writing. "
                "tutorial — a focused how-to requiring no original project."
            ),
        },
        "difficulty": {
            "type": "STRING",
            "description": (
                "starter — 1-2 evenings, 1-2 tools, one clear concept. "
                "weekend — a full weekend, 2-3 tools, a small system or integration. "
                "ambitious — multi-week, complex architecture. Use sparingly."
            ),
        },
        "title_concept": {
            "type": "STRING",
            "description": (
                "Clear, human-readable title. No buzzword stacking. "
                "Should describe what the reader will learn or build, not just sound impressive."
            ),
        },
        "the_build": {
            "type": "STRING",
            "description": (
                "What gets built, described plainly and MVP-scoped to the difficulty level. "
                "Starter ideas: max 2 integrated tools. "
                "Weekend ideas: max 3 integrated tools. "
                "Do not describe the full production version — describe the smallest useful thing."
            ),
        },
        "the_narrative": {
            "type": "STRING",
            "description": (
                "The story arc: what problem prompted this, what was tried, what was learned. "
                "This is what makes the post readable — be honest about friction and tradeoffs."
            ),
        },
        "the_selling_point": {
            "type": "STRING",
            "description": (
                "One sentence: why would a reader care? What will they take away? "
                "Think in terms of a skill gained, a problem solved, or a pattern recognized."
            ),
        },
    },
    "required": [
        "project_type",
        "difficulty",
        "title_concept",
        "the_build",
        "the_narrative",
        "the_selling_point",
    ],
}

# Idea expander uses a simpler schema (no difficulty — user sets that via UI)
_EXPANDER_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "project_type": {
            "type": "STRING",
            "description": "existing_asset or new_build",
        },
        "title_concept": {"type": "STRING"},
        "the_build": {
            "type": "STRING",
            "description": "Technical architecture and tools used",
        },
        "the_narrative": {
            "type": "STRING",
            "description": "Core story — what problem this solves and why it matters",
        },
        "the_selling_point": {
            "type": "STRING",
            "description": "Why a hiring manager or senior engineer cares",
        },
    },
    "required": [
        "project_type", "title_concept",
        "the_build", "the_narrative", "the_selling_point",
    ],
}


# ── DIFFICULTY HELPERS ────────────────────────────────────────────────────────

def _summarize_recent_difficulties(existing_titles: list[str] | None) -> str:
    """
    Placeholder hook. In the future this could accept a list of
    (title, difficulty) tuples from the DB so the agent knows if recent
    batches were too ambitious and should rebalance toward starter ideas.
    For now it returns an empty string.
    """
    return ""


def _validate_difficulty_distribution(blueprints: list[dict]) -> list[dict]:
    """
    Post-generation guard. If the model ignored the distribution rules and
    returned more than 1 ambitious idea, demote the extras to 'weekend'
    so the backlog stays balanced. Logs a warning so the prompt can be
    tuned if this fires frequently.

    Also ensures every blueprint has a difficulty field, defaulting to
    'weekend' if the model omitted it.
    """
    for bp in blueprints:
        if "difficulty" not in bp or bp["difficulty"] not in ("starter", "weekend", "ambitious"):
            bp["difficulty"] = "weekend"
            log.warning("Blueprint missing valid difficulty, defaulted to 'weekend': %s", bp.get("title_concept"))

    ambitious = [bp for bp in blueprints if bp["difficulty"] == "ambitious"]
    if len(ambitious) > 1:
        log.warning(
            "Researcher returned %d ambitious ideas (max 1). Demoting extras to 'weekend'.",
            len(ambitious),
        )
        # Keep the first ambitious idea, demote the rest
        for bp in ambitious[1:]:
            bp["difficulty"] = "weekend"

    return blueprints


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 0 — README WRITER
# ─────────────────────────────────────────────────────────────────────────────

def agent_readme_writer(
    project_name: str,
    file_summaries: list[dict],
    description: str = "",
) -> str:
    """
    Generates a project-level README from file narrations.

    Args:
        project_name: human-friendly project name
        file_summaries: [{"path": "routers/finance.py", "narration": "..."}, ...]
        description: optional human note about what the project does

    Returns:
        Full README.md content as a string
    """
    system = """
You are a Senior DevOps Engineer. Write a clean, standard Markdown README.md
for a code repository based on per-file technical summaries provided to you.

Do NOT explain low-level code logic — treat each file as a black box and focus on:
1. Project Title & one-paragraph Overview
2. Architecture diagram (ASCII is fine)
3. Key Modules — one bullet per file summary provided
4. Prerequisites (Python version, libraries, tools)
5. Environment Variables required
6. How to run / deploy (Docker commands if applicable)
7. Folder structure

Keep it professional and concise. No fluff.
"""
    summary_block = "\n\n".join(
        f"**{s['path']}**\n{s['narration']}" for s in file_summaries
    )
    prompt = (
        f"Project: {project_name}\n"
        f"Description: {description or 'Not provided'}\n\n"
        f"File summaries:\n{summary_block}"
    )
    return _gemini_flash(system, prompt)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 1 — RESEARCHER
# ─────────────────────────────────────────────────────────────────────────────

def agent_researcher(
    interests: str,
    existing_projects: str,
    file_narrations: list[dict] | None = None,
    existing_titles: list[str] | None = None,
    difficulty_context: str = "",
) -> list[dict]:
    """
    Generates 5 blog post blueprints with explicit difficulty tagging and
    a balanced mix of idea types.

    Distribution target per batch:
      Difficulty : 2 starter, 2 weekend, 1 ambitious
      Type       : 1 existing_asset, 3 new_build, 1 tutorial

    At least 2 ideas should be in domains unrelated to the author's existing
    projects (e.g. sports, music, food, movies) to push net-new project work.

    Args:
        interests: comma-separated topics the author cares about
        existing_projects: brief description of current projects
        file_narrations: optional [{"path": str, "narration": str}] from code_files
        existing_titles: list of already-generated idea titles to avoid duplicating

    Returns:
        List of 5 blueprint dicts, each including a 'difficulty' field
    """
    system = """
You are a senior Developer Advocate and Content Strategist helping a data
professional build a consistent, readable blog portfolio.

Your job is to generate blog post blueprints that are REALISTIC TO BUILD AND WRITE.
A great blog post is not about the most complex system — it is about a clear
problem, an honest build story, and a genuine lesson. Senior thinking shows
in the quality of explanation, not in the number of integrated services.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DIFFICULTY — you MUST produce exactly this distribution in every batch:
  • 2 ideas tagged difficulty: "starter"
      Completable in 1–2 evenings. Uses 1–2 tools. Teaches exactly one
      clear concept. The build described must be something a reader could
      reproduce in a single sitting. MAXIMUM 2 integrations.
      Example scope: a Python script that reads a CSV and produces a chart,
      a single FastAPI endpoint that calls one external API, a SQL query
      pattern explained with a real dataset.

  • 2 ideas tagged difficulty: "weekend"
      Completable over a weekend. Uses 2–3 tools. Teaches a small system
      or integration pattern. A motivated reader could finish the MVP in
      two days. MAXIMUM 3 integrations.
      Example scope: a small Airflow DAG that pulls data from one API into
      a local DB, a basic HTMX + FastAPI feature end-to-end, a simple
      Streamlit dashboard over a local dataset.

  • 1 idea tagged difficulty: "ambitious"
      A multi-week project. Complex architecture acceptable. Include this
      to keep the backlog interesting, but do NOT let it dominate.
      Even here, describe the MVP first — not the fully productionized version.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDEA TYPE — you MUST produce exactly this mix in every batch:
  • 1 idea type: "existing_asset"
      Something already built. The article is retrospective — decisions made,
      what worked, what didn't, what you'd change. No new build required.

  • 3 ideas type: "new_build"
      A net-new project to build before writing the article.
      Scope the build to the difficulty tag — do not describe
      a 5-service architecture for a starter idea.

  • 1 idea type: "tutorial"
      A focused how-to. No original project required.
      Explains one technique, tool, or concept using the author's existing
      experience as the lens. These are low-friction to write and get
      high search traffic. Examples: "How I use SQL window functions for X",
      "Async SQLAlchemy patterns that tripped me up", "Debugging Airflow DAGs
      without losing your mind."

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DOMAIN SPREAD — across the 5 ideas:
  • At least 2 ideas must be in domains OUTSIDE the author's existing projects
    (sports analytics, music, food, movies, general Python, career/job market).
    These push the author to build something genuinely new.
  • No more than 2 ideas in the same domain within a single batch.
  • Mix technical tools and subject matter across the batch.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TITLE QUALITY:
  • Clear and human-readable. A reader should understand the topic immediately.
  • No buzzword stacking (e.g. avoid "Multi-Agent Autonomous Orchestration Layer").
  • Describe what the reader will learn or build, not just what sounds impressive.
  • Good: "Building a Simple NBA Stats Tracker with Python and SQLite"
  • Bad: "Orchestrating Multi-Dimensional Basketball Intelligence via Vertex AI Embeddings"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BUILD DESCRIPTION (the_build):
  • Describe the MVP — the smallest version that makes the article worth writing.
  • For starter: name the 1–2 tools, describe what data goes in and what comes out.
  • For weekend: describe the flow in plain terms, not in enterprise architecture terms.
  • For ambitious: still start with the MVP — complexity can be added in follow-up posts.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NARRATIVE (the_narrative):
  • This is the most important field for a readable post.
  • What problem prompted this? What did you try first? What surprised you?
  • Be honest about friction and tradeoffs — that's what readers relate to.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Ideas must be meaningfully distinct from each other AND from the existing
titles provided. Do not suggest near-duplicates.
"""

    narration_block = ""
    if file_narrations:
        narration_block = "\n\nRecent code context (for existing_asset and tutorial ideas):\n" + "\n\n".join(
            f"{n['path']}: {n['narration'][:400]}" for n in file_narrations[:10]
        )

    existing_block = ""
    if existing_titles:
        existing_block = "\n\nAlready in backlog — do NOT suggest similar topics:\n" + \
            "\n".join(f"- {t}" for t in existing_titles[:30])

    # difficulty_context is passed in from the DAG (based on recent DB history).
    # Fall back to the stub helper if called directly (e.g. from tests or BYOI).
    if not difficulty_context:
        difficulty_context = _summarize_recent_difficulties(existing_titles)

    recent_difficulty_note = (
        f"\n{difficulty_context}" if difficulty_context else ""
    )

    prompt = (
        f"Generate exactly 5 blog blueprints.\n\n"
        f"Follow the difficulty distribution (2 starter, 2 weekend, 1 ambitious) "
        f"and type mix (1 existing_asset, 3 new_build, 1 tutorial) precisely.\n\n"
        f"Author interests: {interests}\n\n"
        f"Existing projects (for context and existing_asset ideas):\n{existing_projects}\n"
        f"{recent_difficulty_note}"
        f"{existing_block}"
        f"{narration_block}\n\n"
        f"REMINDER: At least 2 of the 5 ideas must be in domains unrelated to the "
        f"existing projects listed above. At least 1 starter idea must be something "
        f"a reader could reproduce in a single evening with minimal setup."
    )

    schema = {
        "type": "ARRAY",
        "items": _BLUEPRINT_ITEM_SCHEMA,
    }

    raw = _gemini_pro_json(system, prompt, schema)
    blueprints = json.loads(raw)

    # Enforce the distribution as a safety net
    blueprints = _validate_difficulty_distribution(blueprints)

    return blueprints


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 2 — CODE NARRATOR
# ─────────────────────────────────────────────────────────────────────────────

def agent_code_narrator(code_content: str, file_name: str, readme_context: str = "") -> str:
    """
    Reads a single script and produces a technical narration for agent consumption.
    Output is used by: Ghostwriter, README Writer, Researcher, Idea Expander.

    Args:
        code_content: raw source code
        file_name: e.g. "finance.py"
        readme_context: optional existing README or project description

    Returns:
        Markdown narration (NOT a blog post — a technical summary for agents)
    """
    system = """
You are a Principal Data Engineer reviewing code written by a colleague.
Your job is to produce a structured technical narration of the code for use
by other AI agents (not for human readers directly).

Focus on:
- What this file does in 1-2 sentences (the purpose)
- Key data flows: what comes in, what goes out, what is transformed
- Notable architectural choices and why they matter
- Any clever patterns, workarounds, or non-obvious logic
- External dependencies (APIs, DBs, third-party libs) and how they're used
- Potential gotchas or things a developer should know before modifying this file

Do NOT explain basic syntax. Assume the reader is a senior engineer.
Format as Markdown. Keep it under 600 words.
"""
    prompt = (
        f"File: {file_name}\n"
        f"{'Project context: ' + readme_context + chr(10) if readme_context else ''}"
        f"Code:\n{code_content}"
    )
    return _gemini_flash_2_5(system, prompt)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 3 — GHOSTWRITER
# ─────────────────────────────────────────────────────────────────────────────

def agent_ghostwriter(
    blueprint: dict,
    author_notes: str,
    code_narrative: str,
) -> str:
    """
    Writes a 70-80% complete first draft of a blog post.

    Args:
        blueprint: dict with title_concept, the_build, the_narrative,
                   the_selling_point, and optionally difficulty
        author_notes: HITL notes from the author (code snippets, lessons, results)
        code_narrative: output from Code Narrator for the relevant file

    Returns:
        Draft blog post in Markdown
    """
    difficulty = blueprint.get("difficulty", "weekend")
    difficulty_guidance = {
        "starter": (
            "This is a STARTER post. Keep it focused and accessible. "
            "Target length: 800–1200 words. One core concept, explained clearly. "
            "A beginner should be able to follow along."
        ),
        "weekend": (
            "This is a WEEKEND PROJECT post. Balanced depth and readability. "
            "Target length: 1200–1800 words. Walk through the key implementation "
            "decisions without turning into a reference manual."
        ),
        "ambitious": (
            "This is an AMBITIOUS post. Technical depth is appropriate here. "
            "Target length: 1500–2200 words. Cover the architecture, the tradeoffs, "
            "and the non-obvious lessons. Assume a senior reader."
        ),
    }.get(difficulty, "Target length: 1200–1800 words.")

    system = f"""
You are an expert Technical Ghostwriter for a data engineering blog.
Write a draft that is engaging, technically credible, and authentic.

{difficulty_guidance}

Rules:
- Match the tone of a senior engineer writing for peers: direct, no fluff
- Use clear headings, bold for key terms, and fenced code blocks for any code
- Avoid clichés: no "In conclusion", "In today's world", "game-changer"
- Structure: Hook → Problem → Build → Key Insight → Result → Takeaway
- Leave room for the author's voice — don't over-polish
- If this is a tutorial, emphasize the "why" behind each step, not just the "how"
"""
    prompt = (
        f"Blueprint:\n{json.dumps(blueprint, indent=2)}\n\n"
        f"Author's notes and results:\n{author_notes or 'None provided'}\n\n"
        f"Technical code breakdown:\n{code_narrative or 'None provided'}"
    )
    return _groq_llama(system, prompt, temperature=0.7)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 4 — REFINER
# ─────────────────────────────────────────────────────────────────────────────

def agent_refiner(original_draft: str, user_feedback: str) -> str:
    """
    Integrates the author's review feedback into the draft.

    Args:
        original_draft: draft_v1 from Ghostwriter
        user_feedback: author's notes from the HITL review step in LifeOS UI

    Returns:
        Revised draft in Markdown (draft_v2)
    """
    system = """
You are a professional Technical Editor. You receive a blog post draft and
specific feedback from the author. Integrate the feedback precisely:
- If the author asks to change a section, change it
- If they ask to add something, add it
- If they ask to remove something, remove it
- Preserve the author's voice — do not over-polish
- Output the complete revised draft in Markdown, nothing else
"""
    prompt = (
        f"Original draft:\n{original_draft}\n\n"
        f"Author feedback:\n{user_feedback}"
    )
    return _gemini_flash(system, prompt)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 5 — EDITOR & SEO SPECIALIST
# ─────────────────────────────────────────────────────────────────────────────

def agent_editor(draft_content: str) -> str:
    """
    Performs final polish, formatting, and SEO optimization.

    Args:
        draft_content: draft_v2 from Refiner (or draft_v1 if skipped)

    Returns:
        Structured string with SEO header block + final article.
        Format:
            ---
            Title: [final title]
            Meta Description: [150-char description]
            Tags: [tag1, tag2, tag3]
            ---
            [full polished Markdown article]
    """
    system = """
You are a strict Managing Editor and SEO Specialist for a technical publication.

Tasks:
1. Fix any narrative inconsistencies or repetitive phrasing
2. Ensure Markdown formatting is flawless (especially code blocks and headings)
3. Generate a highly clickable, professional final title (max 80 chars)
4. Generate a 150-character SEO meta description
5. Generate 5-7 comma-separated tags relevant to the content

Your output MUST follow this exact format with no deviation:
---
Title: [Title here]
Meta Description: [Description here]
Tags: [tag1, tag2, tag3, tag4, tag5]
---

[Full polished Markdown article here]
"""
    prompt = f"Polish this draft:\n\n{draft_content}"
    return _gemini_flash(system, prompt)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 6 — IDEA EXPANDER (BYOI — Bring Your Own Idea)
# ─────────────────────────────────────────────────────────────────────────────

def agent_idea_expander(user_idea: str) -> dict:
    """
    Takes rough user notes, code snippets, or raw ideas from the LifeOS UI
    and structures them into a full blog blueprint.

    Args:
        user_idea: free-form text from the BYOI modal

    Returns:
        Single blueprint dict
    """
    system = """
You are a senior Developer Advocate and Content Strategist.
The user has provided rough notes, code, or a starter idea for a blog post.
Analyze the input and structure it into a complete, compelling article blueprint.
Be specific about the technical stack mentioned. Infer project_type from context:
if the user describes something already built, use existing_asset; otherwise new_build.
"""
    prompt = f"Expand this idea into a full blueprint:\n\n{user_idea}"

    raw = _gemini_pro_json(system, prompt, _EXPANDER_SCHEMA)
    return json.loads(raw)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 7 — CODE COMMENTER
# ─────────────────────────────────────────────────────────────────────────────

def agent_code_commenter(code_content: str, file_name: str) -> str:
    """
    Adds comments and docstrings to a Python file without changing any logic.

    Args:
        code_content: raw source code
        file_name: e.g. "finance.py"

    Returns:
        Complete file content with comments added — same logic, more readable
    """
    system = """
You are a Senior Python Engineer performing a documentation pass.
Your ONLY job is to add comments and docstrings. Do NOT change any logic,
rename variables, reorder code, or refactor anything whatsoever.

Rules:
- Add a module-level docstring at the top explaining the file's purpose and role
- Add a Google-style docstring to every function and class that lacks one
  (Args, Returns, Raises sections where relevant)
- Add inline comments on non-obvious logic: complex queries, tricky conditionals,
  math, API call structures, async patterns
- Do NOT comment obvious lines like `return result`, `session.commit()`,
  simple assignments, or standard library usage
- Preserve all existing comments exactly as-is
- Output the COMPLETE file with comments added. No preamble, no explanation.
"""
    prompt = f"Add comments and docstrings to {file_name}:\n\n{code_content}"
    return _gemini_flash(system, prompt)


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 8 — CODE IMPROVER
# ─────────────────────────────────────────────────────────────────────────────

def agent_code_improver(
    code_content: str,
    file_name: str,
    narration: str = "",
) -> str:
    """
    Analyzes a Python file and produces a structured improvement report.
    Does NOT rewrite the code — only proposes changes for human review.

    Args:
        code_content: raw source code
        file_name: e.g. "finance.py"
        narration: optional Code Narrator output for context

    Returns:
        Markdown improvement report with one section per suggestion
    """
    system = """
You are a Principal Python Engineer doing a thorough code review.
Produce a structured improvement report — do NOT rewrite the code.

For each suggestion, provide exactly:
## [Short title of the issue]
**Lines:** [line range or function name]
**Category:** Performance | Readability | Correctness | Security | Maintainability
**Severity:** Low | Medium | High
**Problem:** [1-2 sentences explaining the issue]
**Suggestion:** [concrete alternative with a short code snippet in a fenced block]

Focus on real issues. Skip style nitpicks unless they cause actual friction.
Order by severity (High first). Maximum 10 suggestions per file.
"""
    prompt = (
        f"File: {file_name}\n"
        f"{'Context: ' + narration[:500] + chr(10) if narration else ''}"
        f"Code:\n{code_content}"
    )
    return _gemini_flash(system, prompt)
