-- Reference DDL generated from domains/nba/models.py (WO#33).
-- Convenience sanity-check only -- the real Alembic migration is the source of truth.

CREATE TABLE nba_teams (
	id INTEGER NOT NULL, 
	tricode VARCHAR(3) NOT NULL, 
	full_name VARCHAR(60) NOT NULL, 
	conference VARCHAR(10), 
	division VARCHAR(20), 
	PRIMARY KEY (id), 
	UNIQUE (tricode)
);

CREATE TABLE nba_players (
	person_id INTEGER NOT NULL, 
	full_name VARCHAR(120) NOT NULL, 
	team_id INTEGER, 
	roster_status INTEGER, 
	from_year VARCHAR(4), 
	to_year VARCHAR(4), 
	PRIMARY KEY (person_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id)
);

CREATE TABLE nba_games (
	game_id VARCHAR(12) NOT NULL, 
	season VARCHAR(7), 
	game_date DATE NOT NULL, 
	game_status INTEGER, 
	game_status_text VARCHAR(40), 
	home_team_id INTEGER, 
	away_team_id INTEGER, 
	home_score INTEGER, 
	away_score INTEGER, 
	home_wins INTEGER, 
	home_losses INTEGER, 
	away_wins INTEGER, 
	away_losses INTEGER, 
	period INTEGER, 
	duration VARCHAR(10), 
	arena_name VARCHAR(80), 
	arena_city VARCHAR(60), 
	arena_state VARCHAR(20), 
	attendance INTEGER, 
	game_label VARCHAR(60), 
	game_sub_label VARCHAR(60), 
	series_text VARCHAR(60), 
	PRIMARY KEY (game_id), 
	FOREIGN KEY(home_team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(away_team_id) REFERENCES nba_teams (id)
);

CREATE TABLE nba_box_score_traditional (
	minutes VARCHAR(10), 
	field_goals_made INTEGER, 
	field_goals_attempted INTEGER, 
	field_goal_percentage FLOAT, 
	three_pointers_made INTEGER, 
	three_pointers_attempted INTEGER, 
	three_pointer_percentage FLOAT, 
	free_throws_made INTEGER, 
	free_throws_attempted INTEGER, 
	free_throw_percentage FLOAT, 
	rebounds_offensive INTEGER, 
	rebounds_defensive INTEGER, 
	rebounds_total INTEGER, 
	assists INTEGER, 
	steals INTEGER, 
	blocks INTEGER, 
	turnovers INTEGER, 
	fouls_personal INTEGER, 
	points INTEGER, 
	plus_minus FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_trad_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_advanced (
	minutes VARCHAR(10), 
	estimated_offensive_rating FLOAT, 
	offensive_rating FLOAT, 
	estimated_defensive_rating FLOAT, 
	defensive_rating FLOAT, 
	estimated_net_rating FLOAT, 
	net_rating FLOAT, 
	assist_percentage FLOAT, 
	assist_to_turnover FLOAT, 
	assist_ratio FLOAT, 
	offensive_rebound_percentage FLOAT, 
	defensive_rebound_percentage FLOAT, 
	rebound_percentage FLOAT, 
	turnover_ratio FLOAT, 
	effective_field_goal_percentage FLOAT, 
	true_shooting_percentage FLOAT, 
	usage_percentage FLOAT, 
	estimated_usage_percentage FLOAT, 
	estimated_pace FLOAT, 
	pace FLOAT, 
	pace_per_40 FLOAT, 
	possessions FLOAT, 
	pie FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_adv_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_misc (
	minutes VARCHAR(10), 
	points_off_turnovers INTEGER, 
	points_second_chance INTEGER, 
	points_fast_break INTEGER, 
	points_paint INTEGER, 
	opp_points_off_turnovers INTEGER, 
	opp_points_second_chance INTEGER, 
	opp_points_fast_break INTEGER, 
	opp_points_paint INTEGER, 
	blocks INTEGER, 
	blocks_against INTEGER, 
	fouls_personal INTEGER, 
	fouls_drawn INTEGER, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_misc_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_scoring (
	minutes VARCHAR(10), 
	pct_field_goals_attempted_2pt FLOAT, 
	pct_field_goals_attempted_3pt FLOAT, 
	pct_points_2pt FLOAT, 
	pct_points_midrange_2pt FLOAT, 
	pct_points_3pt FLOAT, 
	pct_points_fast_break FLOAT, 
	pct_points_free_throw FLOAT, 
	pct_points_off_turnovers FLOAT, 
	pct_points_paint FLOAT, 
	pct_assisted_2pt FLOAT, 
	pct_unassisted_2pt FLOAT, 
	pct_assisted_3pt FLOAT, 
	pct_unassisted_3pt FLOAT, 
	pct_assisted_fgm FLOAT, 
	pct_unassisted_fgm FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_score_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_usage (
	minutes VARCHAR(10), 
	usage_percentage FLOAT, 
	pct_field_goals_made FLOAT, 
	pct_field_goals_attempted FLOAT, 
	pct_three_pointers_made FLOAT, 
	pct_three_pointers_attempted FLOAT, 
	pct_free_throws_made FLOAT, 
	pct_free_throws_attempted FLOAT, 
	pct_rebounds_offensive FLOAT, 
	pct_rebounds_defensive FLOAT, 
	pct_rebounds_total FLOAT, 
	pct_assists FLOAT, 
	pct_turnovers FLOAT, 
	pct_steals FLOAT, 
	pct_blocks FLOAT, 
	pct_blocks_allowed FLOAT, 
	pct_personal_fouls FLOAT, 
	pct_personal_fouls_drawn FLOAT, 
	pct_points FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_usage_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_fourfactors (
	minutes VARCHAR(10), 
	effective_field_goal_percentage FLOAT, 
	free_throw_attempt_rate FLOAT, 
	team_turnover_percentage FLOAT, 
	offensive_rebound_percentage FLOAT, 
	opp_effective_field_goal_percentage FLOAT, 
	opp_free_throw_attempt_rate FLOAT, 
	opp_team_turnover_percentage FLOAT, 
	opp_offensive_rebound_percentage FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_four_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_tracking (
	minutes VARCHAR(10), 
	distance FLOAT, 
	rebound_chances_offensive INTEGER, 
	rebound_chances_defensive INTEGER, 
	rebound_chances_total INTEGER, 
	touches INTEGER, 
	secondary_assists INTEGER, 
	free_throw_assists INTEGER, 
	passes INTEGER, 
	assists INTEGER, 
	contested_field_goals_made INTEGER, 
	contested_field_goals_attempted INTEGER, 
	contested_field_goal_percentage FLOAT, 
	uncontested_field_goals_made INTEGER, 
	uncontested_field_goals_attempted INTEGER, 
	uncontested_field_goal_percentage FLOAT, 
	field_goal_percentage FLOAT, 
	defended_at_rim_field_goals_made INTEGER, 
	defended_at_rim_field_goals_attempted INTEGER, 
	defended_at_rim_field_goal_percentage FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_track_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_hustle (
	minutes VARCHAR(10), 
	points INTEGER, 
	contested_shots INTEGER, 
	contested_shots_2pt INTEGER, 
	contested_shots_3pt INTEGER, 
	deflections INTEGER, 
	charges_drawn INTEGER, 
	screen_assists INTEGER, 
	screen_assist_points INTEGER, 
	loose_balls_recovered_offensive INTEGER, 
	loose_balls_recovered_defensive INTEGER, 
	loose_balls_recovered_total INTEGER, 
	offensive_box_outs INTEGER, 
	defensive_box_outs INTEGER, 
	box_out_player_team_rebounds INTEGER, 
	box_out_player_rebounds INTEGER, 
	box_outs INTEGER, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_hustle_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_matchup (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	defender_person_id INTEGER NOT NULL, 
	defender_position VARCHAR(10), 
	offensive_person_id INTEGER NOT NULL, 
	matchup_minutes VARCHAR(10), 
	matchup_minutes_sort FLOAT, 
	partial_possessions FLOAT, 
	pct_defender_total_time FLOAT, 
	pct_offensive_total_time FLOAT, 
	pct_total_time_both_on FLOAT, 
	switches_on INTEGER, 
	player_points INTEGER, 
	team_points INTEGER, 
	matchup_assists INTEGER, 
	matchup_potential_assists INTEGER, 
	matchup_turnovers INTEGER, 
	matchup_blocks INTEGER, 
	matchup_field_goals_made INTEGER, 
	matchup_field_goals_attempted INTEGER, 
	matchup_field_goals_percentage FLOAT, 
	matchup_three_pointers_made INTEGER, 
	matchup_three_pointers_attempted INTEGER, 
	matchup_three_pointers_percentage FLOAT, 
	help_blocks INTEGER, 
	help_field_goals_made INTEGER, 
	help_field_goals_attempted INTEGER, 
	help_field_goals_percentage FLOAT, 
	matchup_free_throws_made INTEGER, 
	matchup_free_throws_attempted INTEGER, 
	shooting_fouls INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_matchup_game_pair UNIQUE (game_id, defender_person_id, offensive_person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(defender_person_id) REFERENCES nba_players (person_id), 
	FOREIGN KEY(offensive_person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_box_score_defensive (
	matchup_minutes VARCHAR(10), 
	partial_possessions FLOAT, 
	switches_on INTEGER, 
	player_points INTEGER, 
	defensive_rebounds INTEGER, 
	matchup_assists INTEGER, 
	matchup_turnovers INTEGER, 
	steals INTEGER, 
	blocks INTEGER, 
	matchup_field_goals_made INTEGER, 
	matchup_field_goals_attempted INTEGER, 
	matchup_field_goal_percentage FLOAT, 
	matchup_three_pointers_made INTEGER, 
	matchup_three_pointers_attempted INTEGER, 
	matchup_three_pointer_percentage FLOAT, 
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	team_id INTEGER, 
	person_id INTEGER, 
	position VARCHAR(10), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bs_def_game_player UNIQUE (game_id, person_id), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

CREATE TABLE nba_play_by_play (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	game_id VARCHAR(12) NOT NULL, 
	action_number INTEGER NOT NULL, 
	action_id INTEGER, 
	period INTEGER, 
	clock VARCHAR(20), 
	team_id INTEGER, 
	team_tricode VARCHAR(3), 
	person_id INTEGER, 
	player_name VARCHAR(80), 
	action_type VARCHAR(40), 
	sub_type VARCHAR(40), 
	description TEXT, 
	score_home INTEGER, 
	score_away INTEGER, 
	points_total INTEGER, 
	shot_distance INTEGER, 
	shot_result VARCHAR(10), 
	shot_value INTEGER, 
	is_field_goal BOOL, 
	location VARCHAR(2), 
	shot_x INTEGER, 
	shot_y INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_pbp_game_action UNIQUE (game_id, action_number), 
	FOREIGN KEY(game_id) REFERENCES nba_games (game_id), 
	FOREIGN KEY(team_id) REFERENCES nba_teams (id), 
	FOREIGN KEY(person_id) REFERENCES nba_players (person_id)
);

